<a href="https://colab.research.google.com/github/renzotaco/datascience/blob/main/WebScrapCovid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install texttable

Collecting texttable
  Downloading texttable-1.6.4-py2.py3-none-any.whl (10 kB)
Installing collected packages: texttable
Successfully installed texttable-1.6.4

In [3]:
import requests
from bs4 import BeautifulSoup

url = 'https://www.worldometers.info/coronavirus/countries-where-coronavirus-has-spread/'

page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')
data = []
data_iterator = iter(soup.find_all('td'))
 
while True:
    try:
        country = next(data_iterator).text
        confirmed = next(data_iterator).text
        deaths = next(data_iterator).text
        continent = next(data_iterator).text
 
         data.append((
            country,
            (confirmed.replace(', ', '')),
            (deaths.replace(', ', '')),
            continent
        ))
     except StopIteration:
        break
 
data.sort(key = lambda row: row[1], reverse = True)

In [6]:
import texttable as tt
table = tt.Texttable()
 
table.add_rows([(None, None, None, None)] + data) 
table.set_cols_align(('c', 'c', 'c', 'c')) 
table.header((' Country ', ' Number of cases ', ' Deaths ', ' Continent '))
 
print(table.draw())

+---------------------------+-------------------+----------+-------------------+
|          Country          |  Number of cases  |  Deaths  |     Continent     |
+===========================+===================+==========+===================+
|          Jordan           |      998,492      |  11,879  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           China           |      99,454       |  4,636   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Greece           |      989,814      |  18,982  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|        Kazakhstan         |      977,714      |  12,814  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           Cuba            |      963,428      |  8,311   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Morocco          |      951,092      |  14,794  |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|        Luxembourg         |      93,060       |   889    |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Maldives          |      92,754       |   255    |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Jamaica          |      91,601       |  2,416   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|  Saint Pierre & Miquelon  |        91         |    0     |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Gambia           |       9,998       |   342    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Russia           |     9,925,806     | 286,004  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|        MS Zaandam         |         9         |    2     |                   |
+---------------------------+-------------------+----------+-------------------+
|          Georgia          |      879,368      |  12,582  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           Laos            |      84,503       |   224    |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|     Falkland Islands      |        83         |    0     |   South America   |
+---------------------------+-------------------+----------+-------------------+
|           Nepal           |      823,554      |  11,549  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Turkey           |     8,984,407     |  78,602  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          France           |     8,105,785     | 120,168  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|           Palau           |         8         |    0     | Australia/Oceania |
+---------------------------+-------------------+----------+-------------------+
|    Trinidad and Tobago    |      78,339       |  2,336   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|           Macao           |        77         |    0     |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Slovakia          |      757,492      |  15,179  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|   United Arab Emirates    |      742,567      |  2,149   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Senegal          |      74,054       |  1,886   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Tunisia          |      718,866      |  25,413  |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|         Bulgaria          |      709,537      |  29,279  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|      Cayman Islands       |       7,794       |    9     |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Eritrea          |       7,583       |    62    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|         Gibraltar         |       7,463       |   100    |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|           Niger           |       7,131       |   265    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Lebanon          |      685,162      |  8,814   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Belarus          |      669,631      |  5,227   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Angola           |      65,332       |  1,735   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Croatia          |      644,206      |  11,445  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Réunion          |      63,863       |   391    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|         Guatemala         |      621,328      |  16,020  |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Malawi           |      62,088       |  2,307   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Ireland          |      610,855      |  5,788   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|       Côte d'Ivoire       |      61,857       |   706    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|        Azerbaijan         |      601,028      |  8,038   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|       Guinea-Bissau       |       6,445       |   149    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|       Sierra Leone        |       6,405       |   121    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Germany          |     6,355,888     | 105,010  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|        San Marino         |       6,217       |    94    |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Dominica          |       6,176       |    42    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|           Iran            |     6,147,872     | 130,524  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Vanuatu          |         6         |    1     | Australia/Oceania |
+---------------------------+-------------------+----------+-------------------+
|         DR Congo          |      59,175       |  1,113   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|         Sri Lanka         |      570,672      |  14,555  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|        Costa Rica         |      567,824      |  7,324   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|       Saudi Arabia        |      550,088      |  8,850   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|        Guadeloupe         |      55,284       |   748    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Bolivia          |      547,892      |  19,276  |   South America   |
+---------------------------+-------------------+----------+-------------------+
|          Denmark          |      536,195      |  2,983   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Ecuador          |      530,126      |  33,494  |   South America   |
+---------------------------+-------------------+----------+-------------------+
|          Myanmar          |      525,403      |  19,157  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           Fiji            |      52,567       |   697    | Australia/Oceania |
+---------------------------+-------------------+----------+-------------------+
|         Suriname          |      51,124       |  1,175   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|       United States       |    50,494,319     | 814,580  |   North America   |
+---------------------------+-------------------+----------+-------------------+
|         Eswatini          |      50,337       |  1,248   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Grenada          |       5,910       |   200    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Liberia          |       5,832       |   287    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Bermuda          |       5,760       |   106    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|           Chad            |       5,701       |   181    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
| St. Vincent & Grenadines  |       5,645       |    76    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|         Argentina         |     5,348,123     | 116,708  |   South America   |
+---------------------------+-------------------+----------+-------------------+
|           Spain           |     5,273,178     |  88,321  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|       Liechtenstein       |       5,186       |    65    |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|           Italy           |     5,164,780     | 134,551  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Colombia          |     5,086,381     | 128,929  |   South America   |
+---------------------------+-------------------+----------+-------------------+
|        South Korea        |      496,584      |  4,077   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Lithuania         |      486,224      |  6,920   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|           Syria           |      48,901       |  2,793   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Panama           |      479,901      |  7,381   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|         Paraguay          |      463,522      |  16,488  |   South America   |
+---------------------------+-------------------+----------+-------------------+
|     French Polynesia      |      46,332       |   636    | Australia/Oceania |
+---------------------------+-------------------+----------+-------------------+
|       French Guiana       |      46,304       |   331    |   South America   |
+---------------------------+-------------------+----------+-------------------+
|      Wallis & Futuna      |        454        |    7     | Australia/Oceania |
+---------------------------+-------------------+----------+-------------------+
|        Martinique         |      45,501       |   718    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|        Madagascar         |      44,800       |   972    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|           Sudan           |      44,406       |  3,201   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|        Montserrat         |        44         |    1     |   North America   |
+---------------------------+-------------------+----------+-------------------+
|         Slovenia          |      436,366      |  5,365   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Venezuela         |      436,178      |  5,216   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|    State of Palestine     |      432,921      |  4,558   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Kuwait           |      413,608      |  2,466   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|    Dominican Republic     |      409,490      |  4,214   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Uruguay          |      401,640      |  6,138   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|           Malta           |      40,269       |   468    |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|       Sint Maarten        |       4,617       |    75    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Comoros          |       4,556       |   151    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|         Indonesia         |     4,258,560     | 143,918  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|      Faeroe Islands       |       4,212       |    13    |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|    Antigua and Barbuda    |       4,151       |   117    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Monaco           |       4,006       |    36    |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|     Marshall Islands      |         4         |    0     | Australia/Oceania |
+---------------------------+-------------------+----------+-------------------+
|        Mauritania         |      39,704       |   846    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|         Mongolia          |      384,626      |  2,026   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|        Cabo Verde         |      38,482       |   351    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Guyana           |      38,333       |  1,009   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|         Honduras          |      378,423      |  10,416  |   North America   |
+---------------------------+-------------------+----------+-------------------+
|           Libya           |      376,873      |  5,529   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|         Ethiopia          |      372,711      |  6,819   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|           Gabon           |      37,551       |   281    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Moldova          |      368,497      |  9,315   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|           Egypt           |      365,831      |  20,877  |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|     Papua New Guinea      |      35,835       |   573    | Australia/Oceania |
+---------------------------+-------------------+----------+-------------------+
|          Armenia          |      341,768      |  7,747   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           India           |    34,666,241     | 474,111  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           Oman            |      304,679      |  4,113   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Norway           |      300,013      |  1,134   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Belize           |      30,930       |   585    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Guinea           |      30,798       |   388    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|       Saint Martin        |       3,973       |    56    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Mexico           |     3,908,534     | 295,893  |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Poland           |     3,760,048     |  87,357  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|    Sao Tome & Principe    |       3,733       |    57    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Ukraine          |     3,532,357     |  89,901  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|     Turks and Caicos      |       3,114       |    25    |   North America   |
+---------------------------+-------------------+----------+-------------------+
|       South Africa        |     3,093,452     |  90,060  |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|   Caribbean Netherlands   |       3,082       |    22    |   North America   |